title: "Тренажёр Лазания v1.0"
description: "Тренажёр для лазаний в CatWar, помогающий понять механику местного сапёра."
theme: null   # не подключаем тему Jekyll, используем свой index.html как есть
